data:
    path: /home/ld/Downloads/project/navbox/navBoxPos/data/2022_0811/

navbox: # navbox driver&posSys variable
    init_head: 90 # Angle between satellite and vehicle travel direction
    leverG: [0.5, 0.3, 1.4]
    leverO: [0.7, 0.4, 0.0]

lidar: # hesai driver variable

preprocess:
    filter_num: 2   # Downsampling Point Clouds
    scan_line: 64   # Line number of lidar
    scan_rate: 10   # only need to be set for velodyne, unit: Hz,
    blind: 2        # Remove point cloud within ~ meters

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 180
    det_range: 100.0
    extrinsic_est_en: false # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [-8.086759e-01, 3.195559e-01, -7.997231e-01]
    extrinsic_R:
        [
            9.999976e-01,
            7.553071e-04,
            -2.035826e-03,
            -7.854027e-04,
            9.998898e-01,
            -1.482298e-02,
            2.024406e-03,
            1.482454e-02,
            9.998881e-01,
        ]
